// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVssDJHcSs81rWCEi_Uzg8ZwhSle6T_Zo',
    appId: '1:739851093306:web:4d9add4f429c4c8bcdfc03',
    messagingSenderId: '739851093306',
    projectId: 'emart-app-38a95',
    authDomain: 'emart-app-38a95.firebaseapp.com',
    storageBucket: 'emart-app-38a95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkmeNd2rdAjungnaSNXt4kcmjP9n7-vu0',
    appId: '1:739851093306:android:9b45944939a7d61ecdfc03',
    messagingSenderId: '739851093306',
    projectId: 'emart-app-38a95',
    storageBucket: 'emart-app-38a95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgtWyO9v2qQ9T8L477433tOOP2d3tW_FM',
    appId: '1:739851093306:ios:11007c3726bd2109cdfc03',
    messagingSenderId: '739851093306',
    projectId: 'emart-app-38a95',
    storageBucket: 'emart-app-38a95.appspot.com',
    iosClientId: '739851093306-lut1pgfb8hc9i3i8an24l511elsrgc5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgtWyO9v2qQ9T8L477433tOOP2d3tW_FM',
    appId: '1:739851093306:ios:11007c3726bd2109cdfc03',
    messagingSenderId: '739851093306',
    projectId: 'emart-app-38a95',
    storageBucket: 'emart-app-38a95.appspot.com',
    iosClientId: '739851093306-lut1pgfb8hc9i3i8an24l511elsrgc5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );
}
